### ISSUE TITLE
Desktop does not start if there is another GUI running in the host

### ISSUE THREAD

**Issue by Aerosane** [ehfd/docker-nvidia-glx-desktop#25] opened 2022-06-13 07:24 UTC
Hello,

when I open the port 8080(selkies-gstreamer) URL,I get “502 Bad gateway “ error from nginx,

Thank you,

**Comment by Neoplanetz** [comment] 2022-06-14 04:56
first of all, thank you for sharing docker for nvidia glx desktop.

I'm also same things with @Aerosane 

 I'm running docker with basic command like README

```bash
docker run --gpus 1 -it -e TZ=UTC -e SIZEW=1920 -e SIZEH=1080 -e REFRESH=60 -e DPI=96 -e CDEPTH=24 -e VIDEO_PORT=DFP -e PASSWD=mypasswd -e WEBRTC_ENCODER=nvh264enc -e BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/ehfd/nvidia-glx-desktop:latest
```

after that, I try to access Web VNC, but I cannot access. Error message is ERR_CONNECTION_REFUSED.

I'm already adding 8080 port to my Asus AP.

after some minute later, this docker container is stopped automatically.

 this is the above docker container logs.

```bash
2022-06-10 07:12:31,571 INFO Set uid to user 1000 succeeded
2022-06-10 07:12:31,573 INFO supervisord started with pid 1
2022-06-10 07:12:32,576 INFO spawned: 'entrypoint' with pid 8
2022-06-10 07:12:32,580 INFO spawned: 'pulseaudio' with pid 9
2022-06-10 07:12:32,584 INFO spawned: 'selkies-gstreamer' with pid 10
2022-06-10 07:12:33,720 INFO success: entrypoint entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-10 07:12:33,720 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-10 07:12:33,720 INFO success: selkies-gstreamer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-13 02:13:28,831 INFO Set uid to user 1000 succeeded
2022-06-13 02:13:28,834 INFO supervisord started with pid 1
2022-06-13 02:13:29,837 INFO spawned: 'entrypoint' with pid 8
2022-06-13 02:13:29,841 INFO spawned: 'pulseaudio' with pid 9
2022-06-13 02:13:29,844 INFO spawned: 'selkies-gstreamer' with pid 10
2022-06-13 02:13:29,901 INFO exited: pulseaudio (exit status 1; not expected)
2022-06-13 02:13:31,180 INFO success: entrypoint entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-13 02:13:31,183 INFO spawned: 'pulseaudio' with pid 82
2022-06-13 02:13:31,184 INFO success: selkies-gstreamer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-13 02:13:32,259 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-13 02:19:32,673 WARN received SIGTERM indicating exit request
2022-06-13 02:19:32,674 INFO waiting for entrypoint, pulseaudio, selkies-gstreamer to die
2022-06-13 02:19:35,677 INFO waiting for entrypoint, pulseaudio, selkies-gstreamer to die
2022-06-13 02:19:38,681 INFO waiting for entrypoint, pulseaudio, selkies-gstreamer to die
2022-06-13 02:19:41,685 INFO waiting for entrypoint, pulseaudio, selkies-gstreamer to die

```

how can I resolve this problem?  thank you for reply

**Comment by ehfd** [comment] 2022-06-14 15:11
Some kind of an upstream regression maybe. I cannot check now, but will make sure to fix asap, by next week at the latesr

**Comment by ehfd** [comment] 2022-06-14 15:16
Triggered a rebuild to see if it helps. Please pull the new container and check if it works, if not, manual intervention required.

**Comment by ehfd** [comment] 2022-06-14 15:26
And please upload all three of the .log files at /tmp to troubleshoot quickly.

**Comment by Neoplanetz** [comment] 2022-06-15 02:32
> And please upload all three of the .log files at /tmp to troubleshoot quickly.

I remove old nvidia-glx-desktop docker image and pull new docker image and running docker.

But the current status is also same like before. thus, I upload logs files all here. thank you for fast response

[glx_logs.zip](https://github.com/ehfd/docker-nvidia-glx-desktop/files/8905194/glx_logs.zip)

additionally, docker-nvidia-egl-desktop docker is running smoothly with selkies-gstremer or novnc.

**Comment by ehfd** [comment] 2022-06-15 06:40
For you @Neoplanetz duplicate of https://github.com/ehfd/docker-nvidia-glx-desktop/issues/11
DO NOT START TWO X SERVERS ON ONE GPU
@Aerosane Please check this too

**Comment by Neoplanetz** [comment] 2022-06-15 08:20
sorry for that I don't know about x server well.
I refer #11 . and I change PC with only one rtx 3090 GPU.
I command it 
```bash
$ sudo nvidia-xconfig --no-probe-all-gpus --busid=BUS_ID --only-one-x-screen 
```
and this is /etc/X11/xorg.conf I made using above command automatically.
```bash
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 510.73.05

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BusID          "PCI:1:0:0"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "ProbeAllGpus" "False"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

```
 and I did running nvidia-glx-desktop docker but the result is same.

is it correct to set only one x server on one GPU?

**Comment by Aerosane** [comment] 2022-06-15 08:57
Well,already tried removing my old x server containers,still the results are same.Just tried,but still the same issue.

**Comment by Aerosane** [comment] 2022-06-16 09:10
Still doesn’t work.

**Comment by ehfd** [comment] 2022-06-18 06:19
Until I can get to why this issue persists, docker-nvidia-egl-desktop is still good. Depending on the container toolkit version or driver version, I see that Vulkan now works somehow.

**Comment by Aerosane** [comment] 2022-06-19 10:07
Sure.

**Comment by ehfd** [comment] 2022-06-26 14:38
https://discord.gg/wDNGDeSW5F

For everyone with this issue, please come in here. This is for the [Selkies](https://github.com/selkies-project) project overall, but nonetheless a relevant server for related discussion.

**Comment by ehfd** [comment] 2022-07-03 09:27
I am personally troubleshooting with @Neoplanetz . Anything found here will be posted here and updated to the docs.

**Comment by ehfd** [comment] 2022-07-21 16:37
I have not got enough time to work on this, but I have gotten access to infrastructure that can replicate this. I will be updating soon.

**Comment by ehfd** [comment] 2022-08-18 12:35
In order to use an X server on the host for your monitor with one GPU, and then provision other GPUs for the containers, it is required to change your `/etc/X11/xorg.conf` configurations.
First use `nvidia-xconfig --no-probe-all-gpus --busid=$BUS_ID --only-one-x-screen` to generate `/etc/X11/xorg.conf` where `BUS_ID` is generated with the below script. `GPU_SELECT` is the ID of the specific GPU you want to provision.
```
HEX_ID=$(nvidia-smi --query-gpu=pci.bus_id --id="$GPU_SELECT" --format=csv | sed -n 2p)
IFS=":." ARR_ID=($HEX_ID)
unset IFS
BUS_ID=PCI:$((16#${ARR_ID[1]})):$((16#${ARR_ID[2]})):$((16#${ARR_ID[3]}))
```
Then, edit `/etc/X11/xorg.conf` and add the following to the end.
```
Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection
```
If you restart your OS or the Xorg server, you will now be able to use one GPU for your host X server and your real monitor, and use the rest of the GPUs for the containers.
Use `docker --gpus '"device=1,2"'` to provision GPUs with device IDs 1 and 2 to the container. `--gpus 1` means any one GPU, not device ID of 1. Same for podman.

**Closed** 2022-08-22 11:02 UTC

**Comment by ehfd** [comment] 2022-08-24 08:49
Added in [Documentation](https://github.com/ehfd/docker-nvidia-glx-desktop#troubleshooting).
